hard_tabs = false
tab_spaces = 2
imports_granularity="Module"
reorder_imports = false
max_width = 120
use_small_heuristics = "Off"
wrap_comments = true
fn_params_layout = "Tall"
fn_call_width = 60
chain_width = 60
single_line_if_else = false
force_multiline_blocks = true
